################################################################################
# 自动生成的文件。不要编辑！
################################################################################

-include ../makefile.init

RM := rm -rf

# All of the sources participating in the build are defined here
-include sources.mk
-include rt-thread/src/subdir.mk
-include rt-thread/libcpu/arm/cortex-a/subdir.mk
-include rt-thread/libcpu/arm/common/subdir.mk
-include rt-thread/components/utilities/ulog/backend/subdir.mk
-include rt-thread/components/utilities/ulog/subdir.mk
-include rt-thread/components/net/sal_socket/src/subdir.mk
-include rt-thread/components/net/sal_socket/socket/subdir.mk
-include rt-thread/components/net/sal_socket/impl/subdir.mk
-include rt-thread/components/net/sal_socket/dfs_net/subdir.mk
-include rt-thread/components/net/netdev/src/subdir.mk
-include rt-thread/components/net/lwip-2.0.2/src/netif/subdir.mk
-include rt-thread/components/net/lwip-2.0.2/src/core/ipv4/subdir.mk
-include rt-thread/components/net/lwip-2.0.2/src/core/subdir.mk
-include rt-thread/components/net/lwip-2.0.2/src/arch/subdir.mk
-include rt-thread/components/net/lwip-2.0.2/src/apps/ping/subdir.mk
-include rt-thread/components/net/lwip-2.0.2/src/api/subdir.mk
-include rt-thread/components/lwp/arch/arm/cortex-a/subdir.mk
-include rt-thread/components/lwp/subdir.mk
-include rt-thread/components/libc/time/subdir.mk
-include rt-thread/components/libc/termios/subdir.mk
-include rt-thread/components/libc/signal/subdir.mk
-include rt-thread/components/libc/pthreads/subdir.mk
-include rt-thread/components/libc/mmap/subdir.mk
-include rt-thread/components/libc/libdl/arch/subdir.mk
-include rt-thread/components/libc/libdl/subdir.mk
-include rt-thread/components/libc/compilers/newlib/subdir.mk
-include rt-thread/components/libc/aio/subdir.mk
-include rt-thread/components/finsh/subdir.mk
-include rt-thread/components/drivers/watchdog/subdir.mk
-include rt-thread/components/drivers/src/subdir.mk
-include rt-thread/components/drivers/spi/sfud/src/subdir.mk
-include rt-thread/components/drivers/spi/subdir.mk
-include rt-thread/components/drivers/serial/subdir.mk
-include rt-thread/components/drivers/sdio/subdir.mk
-include rt-thread/components/drivers/rtc/subdir.mk
-include rt-thread/components/drivers/mtd/subdir.mk
-include rt-thread/components/drivers/misc/subdir.mk
-include rt-thread/components/drivers/i2c/subdir.mk
-include rt-thread/components/dfs/src/subdir.mk
-include rt-thread/components/dfs/filesystems/romfs/subdir.mk
-include rt-thread/components/dfs/filesystems/ramfs/subdir.mk
-include rt-thread/components/dfs/filesystems/elmfat/option/subdir.mk
-include rt-thread/components/dfs/filesystems/elmfat/subdir.mk
-include rt-thread/components/dfs/filesystems/devfs/subdir.mk
-include rt-thread/components/cplusplus/subdir.mk
-include packages/libsodium-latest/libsodium/sodium/subdir.mk
-include packages/libsodium-latest/libsodium/randombytes/sysrandom/subdir.mk
-include packages/libsodium-latest/libsodium/randombytes/internal/subdir.mk
-include packages/libsodium-latest/libsodium/randombytes/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_verify/sodium/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/xsalsa20/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/xchacha20/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/salsa208/ref/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/salsa208/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/salsa2012/ref/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/salsa2012/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/salsa20/xmm6int/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/salsa20/xmm6/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/salsa20/ref/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/salsa20/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/chacha20/ref/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/chacha20/dolbeau/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/chacha20/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_stream/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_sign/ed25519/ref10/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_sign/ed25519/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_sign/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_shorthash/siphash24/ref/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_shorthash/siphash24/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_shorthash/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_secretstream/xchacha20poly1305/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_secretbox/xsalsa20poly1305/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_secretbox/xchacha20poly1305/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_secretbox/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_scalarmult/ristretto255/ref10/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_scalarmult/ed25519/ref10/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_scalarmult/curve25519/sandy2x/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_scalarmult/curve25519/ref10/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_scalarmult/curve25519/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_scalarmult/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_pwhash/scryptsalsa208sha256/sse/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_pwhash/scryptsalsa208sha256/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_pwhash/argon2/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_pwhash/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_onetimeauth/poly1305/sse2/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_onetimeauth/poly1305/donna/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_onetimeauth/poly1305/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_onetimeauth/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_kx/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_kdf/hkdf/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_kdf/blake2b/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_kdf/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_hash/sha512/cp/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_hash/sha512/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_hash/sha256/cp/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_hash/sha256/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_hash/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_generichash/blake2b/ref/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_generichash/blake2b/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_generichash/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_core/salsa/ref/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_core/hsalsa20/ref2/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_core/hsalsa20/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_core/hchacha20/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_core/ed25519/ref10/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_core/ed25519/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_box/curve25519xsalsa20poly1305/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_box/curve25519xchacha20poly1305/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_box/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_auth/hmacsha512256/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_auth/hmacsha512/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_auth/hmacsha256/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_auth/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_aead/xchacha20poly1305/sodium/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_aead/chacha20poly1305/sodium/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_aead/aes256gcm/aesni/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_aead/aegis256/armcrypto/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_aead/aegis256/aesni/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_aead/aegis256/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_aead/aegis128l/armcrypto/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_aead/aegis128l/aesni/subdir.mk
-include packages/libsodium-latest/libsodium/crypto_aead/aegis128l/subdir.mk
-include packages/gui_engine-latest/src/subdir.mk
-include packages/gui_engine-latest/libraries/lodepng/subdir.mk
-include packages/gui_engine-latest/example/subdir.mk
-include packages/fal-v1.0.0/src/subdir.mk
-include packages/fal-v1.0.0/samples/porting/subdir.mk
-include drivers/subdir.mk
-include build/packages/gui_engine-latest/src/subdir.mk
-include build/packages/gui_engine-latest/libraries/lodepng/subdir.mk
-include build/packages/gui_engine-latest/example/subdir.mk
-include build/packages/fal-v1.0.0/src/subdir.mk
-include build/packages/fal-v1.0.0/samples/porting/subdir.mk
-include build/kernel/src/subdir.mk
-include build/kernel/libcpu/arm/cortex-a/subdir.mk
-include build/kernel/libcpu/arm/common/subdir.mk
-include build/kernel/components/utilities/ulog/backend/subdir.mk
-include build/kernel/components/utilities/ulog/subdir.mk
-include build/kernel/components/net/sal_socket/src/subdir.mk
-include build/kernel/components/net/sal_socket/socket/subdir.mk
-include build/kernel/components/net/sal_socket/impl/subdir.mk
-include build/kernel/components/net/sal_socket/dfs_net/subdir.mk
-include build/kernel/components/net/netdev/src/subdir.mk
-include build/kernel/components/net/lwip-2.0.2/src/netif/subdir.mk
-include build/kernel/components/net/lwip-2.0.2/src/core/ipv4/subdir.mk
-include build/kernel/components/net/lwip-2.0.2/src/core/subdir.mk
-include build/kernel/components/net/lwip-2.0.2/src/arch/subdir.mk
-include build/kernel/components/net/lwip-2.0.2/src/apps/ping/subdir.mk
-include build/kernel/components/net/lwip-2.0.2/src/api/subdir.mk
-include build/kernel/components/lwp/arch/arm/cortex-a/subdir.mk
-include build/kernel/components/lwp/subdir.mk
-include build/kernel/components/libc/time/subdir.mk
-include build/kernel/components/libc/termios/subdir.mk
-include build/kernel/components/libc/signal/subdir.mk
-include build/kernel/components/libc/pthreads/subdir.mk
-include build/kernel/components/libc/mmap/subdir.mk
-include build/kernel/components/libc/libdl/arch/subdir.mk
-include build/kernel/components/libc/libdl/subdir.mk
-include build/kernel/components/libc/compilers/newlib/subdir.mk
-include build/kernel/components/libc/aio/subdir.mk
-include build/kernel/components/finsh/subdir.mk
-include build/kernel/components/drivers/watchdog/subdir.mk
-include build/kernel/components/drivers/src/subdir.mk
-include build/kernel/components/drivers/spi/sfud/src/subdir.mk
-include build/kernel/components/drivers/spi/subdir.mk
-include build/kernel/components/drivers/serial/subdir.mk
-include build/kernel/components/drivers/sdio/subdir.mk
-include build/kernel/components/drivers/rtc/subdir.mk
-include build/kernel/components/drivers/mtd/subdir.mk
-include build/kernel/components/drivers/misc/subdir.mk
-include build/kernel/components/drivers/i2c/subdir.mk
-include build/kernel/components/dfs/src/subdir.mk
-include build/kernel/components/dfs/filesystems/romfs/subdir.mk
-include build/kernel/components/dfs/filesystems/ramfs/subdir.mk
-include build/kernel/components/dfs/filesystems/elmfat/option/subdir.mk
-include build/kernel/components/dfs/filesystems/elmfat/subdir.mk
-include build/kernel/components/dfs/filesystems/devfs/subdir.mk
-include build/kernel/components/cplusplus/subdir.mk
-include build/drivers/subdir.mk
-include build/applications/subdir.mk
-include applications/subdir.mk
-include subdir.mk
-include objects.mk

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(CC_DEPS)),)
-include $(CC_DEPS)
endif
ifneq ($(strip $(C++_DEPS)),)
-include $(C++_DEPS)
endif
ifneq ($(strip $(C_UPPER_DEPS)),)
-include $(C_UPPER_DEPS)
endif
ifneq ($(strip $(CXX_DEPS)),)
-include $(CXX_DEPS)
endif
ifneq ($(strip $(ASM_DEPS)),)
-include $(ASM_DEPS)
endif
ifneq ($(strip $(S_UPPER_DEPS)),)
-include $(S_UPPER_DEPS)
endif
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
ifneq ($(strip $(CPP_DEPS)),)
-include $(CPP_DEPS)
endif
endif

-include ../makefile.defs

# Add inputs and outputs from these tool invocations to the build variables 
SECONDARY_FLASH += \
rtthread.bin \

SECONDARY_SIZE += \
rtthread.siz \


# 所有目标
all: rtthread.elf secondary-outputs

# 工具调用
rtthread.elf: $(OBJS) $(USER_OBJS)
	arm-none-eabi-g++ -march=armv7-a -marm -mfloat-abi=soft -O0 -Wall  -g -gdwarf-2 -T "D:\RT-ThreadStudio\workspace\rtt-qemu-ota\link.lds" -Xlinker --gc-sections -Wl,-Map,"rtthread.map" -o "rtthread.elf" $(OBJS) $(USER_OBJS) $(LIBS)

rtthread.bin: rtthread.elf
	arm-none-eabi-objcopy -O binary "rtthread.elf"  "rtthread.bin"

rtthread.siz: rtthread.elf
	arm-none-eabi-size --format=berkeley "rtthread.elf"

# 其他目标
clean:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(OBJS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS) rtthread.elf
	-@echo ' '

secondary-outputs: $(SECONDARY_FLASH) $(SECONDARY_SIZE)

.PHONY: all clean dependents

-include ../makefile.targets
