################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
applications \
build/applications \
build/drivers \
build/kernel/components/cplusplus \
build/kernel/components/dfs/filesystems/devfs \
build/kernel/components/dfs/filesystems/elmfat \
build/kernel/components/dfs/filesystems/elmfat/option \
build/kernel/components/dfs/filesystems/ramfs \
build/kernel/components/dfs/filesystems/romfs \
build/kernel/components/dfs/src \
build/kernel/components/drivers/i2c \
build/kernel/components/drivers/misc \
build/kernel/components/drivers/mtd \
build/kernel/components/drivers/rtc \
build/kernel/components/drivers/sdio \
build/kernel/components/drivers/serial \
build/kernel/components/drivers/spi/sfud/src \
build/kernel/components/drivers/spi \
build/kernel/components/drivers/src \
build/kernel/components/drivers/watchdog \
build/kernel/components/finsh \
build/kernel/components/libc/aio \
build/kernel/components/libc/compilers/newlib \
build/kernel/components/libc/libdl/arch \
build/kernel/components/libc/libdl \
build/kernel/components/libc/mmap \
build/kernel/components/libc/pthreads \
build/kernel/components/libc/signal \
build/kernel/components/libc/termios \
build/kernel/components/libc/time \
build/kernel/components/lwp/arch/arm/cortex-a \
build/kernel/components/lwp \
build/kernel/components/net/lwip-2.0.2/src/api \
build/kernel/components/net/lwip-2.0.2/src/apps/ping \
build/kernel/components/net/lwip-2.0.2/src/arch \
build/kernel/components/net/lwip-2.0.2/src/core \
build/kernel/components/net/lwip-2.0.2/src/core/ipv4 \
build/kernel/components/net/lwip-2.0.2/src/netif \
build/kernel/components/net/netdev/src \
build/kernel/components/net/sal_socket/dfs_net \
build/kernel/components/net/sal_socket/impl \
build/kernel/components/net/sal_socket/socket \
build/kernel/components/net/sal_socket/src \
build/kernel/components/utilities/ulog/backend \
build/kernel/components/utilities/ulog \
build/kernel/libcpu/arm/common \
build/kernel/libcpu/arm/cortex-a \
build/kernel/src \
build/packages/fal-v1.0.0/samples/porting \
build/packages/fal-v1.0.0/src \
build/packages/gui_engine-latest/example \
build/packages/gui_engine-latest/libraries/lodepng \
build/packages/gui_engine-latest/src \
drivers \
packages/fal-v1.0.0/samples/porting \
packages/fal-v1.0.0/src \
packages/gui_engine-latest/example \
packages/gui_engine-latest/libraries/lodepng \
packages/gui_engine-latest/src \
packages/libsodium-latest/libsodium/crypto_aead/aegis128l \
packages/libsodium-latest/libsodium/crypto_aead/aegis128l/aesni \
packages/libsodium-latest/libsodium/crypto_aead/aegis128l/armcrypto \
packages/libsodium-latest/libsodium/crypto_aead/aegis256 \
packages/libsodium-latest/libsodium/crypto_aead/aegis256/aesni \
packages/libsodium-latest/libsodium/crypto_aead/aegis256/armcrypto \
packages/libsodium-latest/libsodium/crypto_aead/aes256gcm/aesni \
packages/libsodium-latest/libsodium/crypto_aead/chacha20poly1305/sodium \
packages/libsodium-latest/libsodium/crypto_aead/xchacha20poly1305/sodium \
packages/libsodium-latest/libsodium/crypto_auth \
packages/libsodium-latest/libsodium/crypto_auth/hmacsha256 \
packages/libsodium-latest/libsodium/crypto_auth/hmacsha512 \
packages/libsodium-latest/libsodium/crypto_auth/hmacsha512256 \
packages/libsodium-latest/libsodium/crypto_box \
packages/libsodium-latest/libsodium/crypto_box/curve25519xchacha20poly1305 \
packages/libsodium-latest/libsodium/crypto_box/curve25519xsalsa20poly1305 \
packages/libsodium-latest/libsodium/crypto_core/ed25519 \
packages/libsodium-latest/libsodium/crypto_core/ed25519/ref10 \
packages/libsodium-latest/libsodium/crypto_core/hchacha20 \
packages/libsodium-latest/libsodium/crypto_core/hsalsa20 \
packages/libsodium-latest/libsodium/crypto_core/hsalsa20/ref2 \
packages/libsodium-latest/libsodium/crypto_core/salsa/ref \
packages/libsodium-latest/libsodium/crypto_generichash/blake2b \
packages/libsodium-latest/libsodium/crypto_generichash/blake2b/ref \
packages/libsodium-latest/libsodium/crypto_generichash \
packages/libsodium-latest/libsodium/crypto_hash \
packages/libsodium-latest/libsodium/crypto_hash/sha256/cp \
packages/libsodium-latest/libsodium/crypto_hash/sha256 \
packages/libsodium-latest/libsodium/crypto_hash/sha512/cp \
packages/libsodium-latest/libsodium/crypto_hash/sha512 \
packages/libsodium-latest/libsodium/crypto_kdf/blake2b \
packages/libsodium-latest/libsodium/crypto_kdf \
packages/libsodium-latest/libsodium/crypto_kdf/hkdf \
packages/libsodium-latest/libsodium/crypto_kx \
packages/libsodium-latest/libsodium/crypto_onetimeauth \
packages/libsodium-latest/libsodium/crypto_onetimeauth/poly1305/donna \
packages/libsodium-latest/libsodium/crypto_onetimeauth/poly1305 \
packages/libsodium-latest/libsodium/crypto_onetimeauth/poly1305/sse2 \
packages/libsodium-latest/libsodium/crypto_pwhash/argon2 \
packages/libsodium-latest/libsodium/crypto_pwhash \
packages/libsodium-latest/libsodium/crypto_pwhash/scryptsalsa208sha256 \
packages/libsodium-latest/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
packages/libsodium-latest/libsodium/crypto_pwhash/scryptsalsa208sha256/sse \
packages/libsodium-latest/libsodium/crypto_scalarmult \
packages/libsodium-latest/libsodium/crypto_scalarmult/curve25519/ref10 \
packages/libsodium-latest/libsodium/crypto_scalarmult/curve25519/sandy2x \
packages/libsodium-latest/libsodium/crypto_scalarmult/curve25519 \
packages/libsodium-latest/libsodium/crypto_scalarmult/ed25519/ref10 \
packages/libsodium-latest/libsodium/crypto_scalarmult/ristretto255/ref10 \
packages/libsodium-latest/libsodium/crypto_secretbox \
packages/libsodium-latest/libsodium/crypto_secretbox/xchacha20poly1305 \
packages/libsodium-latest/libsodium/crypto_secretbox/xsalsa20poly1305 \
packages/libsodium-latest/libsodium/crypto_secretstream/xchacha20poly1305 \
packages/libsodium-latest/libsodium/crypto_shorthash \
packages/libsodium-latest/libsodium/crypto_shorthash/siphash24/ref \
packages/libsodium-latest/libsodium/crypto_shorthash/siphash24 \
packages/libsodium-latest/libsodium/crypto_sign \
packages/libsodium-latest/libsodium/crypto_sign/ed25519/ref10 \
packages/libsodium-latest/libsodium/crypto_sign/ed25519 \
packages/libsodium-latest/libsodium/crypto_stream/chacha20/dolbeau \
packages/libsodium-latest/libsodium/crypto_stream/chacha20/ref \
packages/libsodium-latest/libsodium/crypto_stream/chacha20 \
packages/libsodium-latest/libsodium/crypto_stream \
packages/libsodium-latest/libsodium/crypto_stream/salsa20/ref \
packages/libsodium-latest/libsodium/crypto_stream/salsa20 \
packages/libsodium-latest/libsodium/crypto_stream/salsa20/xmm6 \
packages/libsodium-latest/libsodium/crypto_stream/salsa20/xmm6int \
packages/libsodium-latest/libsodium/crypto_stream/salsa2012/ref \
packages/libsodium-latest/libsodium/crypto_stream/salsa2012 \
packages/libsodium-latest/libsodium/crypto_stream/salsa208/ref \
packages/libsodium-latest/libsodium/crypto_stream/salsa208 \
packages/libsodium-latest/libsodium/crypto_stream/xchacha20 \
packages/libsodium-latest/libsodium/crypto_stream/xsalsa20 \
packages/libsodium-latest/libsodium/crypto_verify/sodium \
packages/libsodium-latest/libsodium/randombytes/internal \
packages/libsodium-latest/libsodium/randombytes \
packages/libsodium-latest/libsodium/randombytes/sysrandom \
packages/libsodium-latest/libsodium/sodium \
rt-thread/components/cplusplus \
rt-thread/components/dfs/filesystems/devfs \
rt-thread/components/dfs/filesystems/elmfat \
rt-thread/components/dfs/filesystems/elmfat/option \
rt-thread/components/dfs/filesystems/ramfs \
rt-thread/components/dfs/filesystems/romfs \
rt-thread/components/dfs/src \
rt-thread/components/drivers/i2c \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/mtd \
rt-thread/components/drivers/rtc \
rt-thread/components/drivers/sdio \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/spi/sfud/src \
rt-thread/components/drivers/spi \
rt-thread/components/drivers/src \
rt-thread/components/drivers/watchdog \
rt-thread/components/finsh \
rt-thread/components/libc/aio \
rt-thread/components/libc/compilers/newlib \
rt-thread/components/libc/libdl/arch \
rt-thread/components/libc/libdl \
rt-thread/components/libc/mmap \
rt-thread/components/libc/pthreads \
rt-thread/components/libc/signal \
rt-thread/components/libc/termios \
rt-thread/components/libc/time \
rt-thread/components/lwp/arch/arm/cortex-a \
rt-thread/components/lwp \
rt-thread/components/net/lwip-2.0.2/src/api \
rt-thread/components/net/lwip-2.0.2/src/apps/ping \
rt-thread/components/net/lwip-2.0.2/src/arch \
rt-thread/components/net/lwip-2.0.2/src/core \
rt-thread/components/net/lwip-2.0.2/src/core/ipv4 \
rt-thread/components/net/lwip-2.0.2/src/netif \
rt-thread/components/net/netdev/src \
rt-thread/components/net/sal_socket/dfs_net \
rt-thread/components/net/sal_socket/impl \
rt-thread/components/net/sal_socket/socket \
rt-thread/components/net/sal_socket/src \
rt-thread/components/utilities/ulog/backend \
rt-thread/components/utilities/ulog \
rt-thread/libcpu/arm/common \
rt-thread/libcpu/arm/cortex-a \
rt-thread/src \
. \

